import assert from "node:assert/strict";
import { calculatePlayEnvelopes } from "../../src/level-check/play-envelope.js";
import { composePlayFindings } from "../../src/level-check/play-findings.js";
import { validateLevelCheckRequest } from "../../src/level-check/request.js";
import { requestFixture } from "./fixtures.js";

const base = validateLevelCheckRequest(requestFixture());
const [higher] = calculatePlayEnvelopes(base.playModel!);
assert.equal(higher.min, 20);
assert.equal(higher.max, 100);
assert.equal(higher.expectedValue, 60);
assert.equal(higher.variance, 800);
assert.equal(higher.upside, 40);
assert.equal(higher.downside, 40);
assert.equal(higher.determinant, "mixed");
assert.equal(higher.probabilityStatus, "complete");
assert.equal(composePlayFindings(base, [higher]).differences[0].causeDomain, "unknown");
assert.equal(base.playModel!.scenarios[0].outcomes.length, 3, "no fourth independent combination is manufactured");
const completeFindings = composePlayFindings(base, [higher]);
assert.ok(completeFindings.differences[0].unknowns.length);
assert.equal(completeFindings.gaps.length, 0, "complete model does not gain a spurious condition gap");

const lower = requestFixture();
lower.playModel!.metric.direction = "lower";
lower.playModel!.metric.unit = "seconds";
const s = lower.playModel!.scenarios[0];
s.predictedBaseline = { value: 8, unit: "seconds" };
s.outcomes.forEach((o, i) => { o.value = [4, 8, 12][i]; o.unit = "seconds"; });
const [time] = calculatePlayEnvelopes(validateLevelCheckRequest(lower).playModel!);
assert.equal(time.expectedValue, 8);
assert.equal(time.variance, 8);
assert.equal(time.upside, 4);
assert.equal(time.downside, 4);
s.predictedBaseline.value = 20;
const [outside] = calculatePlayEnvelopes(validateLevelCheckRequest(lower).playModel!);
assert.equal(outside.upside, 16);
assert.equal(outside.downside, 0);

const partial = requestFixture();
partial.playModel!.scenarios[0].exhaustive = false;
const [partialEnvelope] = calculatePlayEnvelopes(validateLevelCheckRequest(partial).playModel!);
assert.equal(partialEnvelope.rangeScope, "enumerated_partial");
assert.equal(partialEnvelope.expectedValue, null);
assert.equal(partialEnvelope.variance, null);
assert.equal(partialEnvelope.probabilityStatus, "non_exhaustive");

const missing = requestFixture();
const missingScenario = missing.playModel!.scenarios[0];
delete missingScenario.outcomes[0].probability;
delete missingScenario.predictedBaseline;
delete missingScenario.skillBand;
missingScenario.assumptions = {};
const missingRequest = validateLevelCheckRequest(missing);
const [missingEnvelope] = calculatePlayEnvelopes(missingRequest.playModel!);
assert.equal(missingEnvelope.expectedValue, null);
assert.equal(missingEnvelope.upside, null);
assert.equal(missingEnvelope.downside, null);
const missingFindings = composePlayFindings(missingRequest, [missingEnvelope]);
assert.ok(missingFindings.gaps[0].unknowns.some((u) => u.includes("技能帯")));
assert.ok(missingFindings.gaps[0].unknowns.some((u) => u.includes("配置")));
assert.ok(missingFindings.gaps[0].unknowns.some((u) => u.includes("適用ルール")));
assert.ok(missingFindings.gaps[0].unknowns.some((u) => u.includes("確率")));
assert.ok(missingFindings.gaps[0].unknowns.some((u) => u.includes("時間")));

const skills = requestFixture();
const expert = structuredClone(skills.playModel!.scenarios[0]);
expert.id = "expert";
expert.skillBand = "上級者";
expert.outcomes.forEach((o) => { o.value += 40; });
skills.playModel!.scenarios.push(expert);
const separate = calculatePlayEnvelopes(validateLevelCheckRequest(skills).playModel!);
assert.deepEqual(separate.map((e) => e.expectedValue), [60, 100]);
assert.deepEqual(separate.map((e) => e.variance), [800, 800], "skill differences are not random variance");

const zero = requestFixture();
zero.playModel!.scenarios[0].outcomes[0].probability = 0;
zero.playModel!.scenarios[0].outcomes[1].probability = 0.75;
assert.equal(calculatePlayEnvelopes(validateLevelCheckRequest(zero).playModel!)[0].min, 60);

const overflow = requestFixture();
overflow.playModel!.scenarios[0].outcomes[0].value = -1e308;
overflow.playModel!.scenarios[0].outcomes[2].value = 1e308;
assert.throws(() => calculatePlayEnvelopes(validateLevelCheckRequest(overflow).playModel!), /overflow/);
console.log("level-check play envelope: all passed");
