import "./interactions.test.js";
import "./signature-verify.test.js";
import "./command-router.test.js";
import "./auto-discussion.test.js";
import "./humanize.test.js";
import "./reactions.test.js";
import "./crawl-channel.test.js";
import "./forum-monitor.test.js";
import "./forum-flow-tags.test.js";
import "./paper-gap-ui.test.js";
import "./facilitator-directives.test.js";
import "./paper-review-ack.test.js";
import "./mechanics-check.test.js";
console.log("discord-hook tests: all passed");
