export const GOLDEN_TEXTS = [
  "最高に面白い!",
  "つまらないしバグだらけ",
  "神ゲー 888888",
  "草",
  "!?",
  "awesome combat but terrible performance",
  "I love the story and beautiful graphics",
  "boring repetitive grind",
  "good value, smooth and polished",
  "worst crash ever!",
  "難しいけど達成感があって楽しい",
  "理不尽でストレスがすごい",
  "物語と世界観が好き",
  "グラフィックは綺麗、でも重い",
  "課金ゲーでがっかり",
  "周回が中毒になる",
  "怖い! でも面白い",
  "まさかの展開ですごい",
  "泣いた。切ない物語",
  "操作が快適でおすすめ",
  "対戦の難易度がちょうど良い",
  "コンテンツ量が少ない",
  "値段は高いがworth it",
  "fps lag and stutter",
  "キャラとシナリオが最高",
  "作画が美麗",
  "リプレイ性が高く何度も遊べる",
  "refund requested",
  "not bad",
  "普通",
  "",
  "!!!",
  "神",
  "クソ",
  "期待している 次回アプデ待ち",
  "安心して遊べる安定した良作",
  "ホラーでビビった",
  "ムカつくほど理不尽",
  "発見が楽しい exploration",
  "story good, gameplay bad",
  "beautiful but overpriced",
  "easy and relaxing",
  "challenging boss was amazing!!",
  "ガチャで最高のキャラが出た!",
  "ガチャ課金は詐欺",
  "やり込みボリュームがある",
  "最適化不足で落ちる",
  "協力プレイが楽しい",
  "期待外れで微妙",
  "masterpiece 名作",
] as const;
